version: 0.2
phases:

  install:
    commands:
      - pip install cfn-lint
      - pip install awscli
  build:
    commands:
      - cfn-lint --template "eq_s3_org_read_only.yml" --regions $AWS_REGION
      #- aws cloudformation validate-template --template-body "file://$(pwd)/eq_s3_org_read_only.yml"
