############################################################
# Create S3 Bucket for DevOPs account
# (c) Enquizit, Inc
# v1.0 2021-12-06
############################################################


AWSTemplateFormatVersion: 2010-09-09

Description: Creates S3 code sharing bucket for organizational DevOps account


############################################################
# Parameters
############################################################
Parameters:

  S3BucketName:
    Type: String
    Description: Root Name of S3 Bucket
    Defaults: acme-devops-code

  OrganizationId:
    Type: String
    Description: Organization Id


############################################################
# Resources
############################################################
Resources:

  # Bucket where code will be deployed. Cannot enable encryption easily without
  # creating a kms key that can be shared between accounts.
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3BucketName}-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  # Bucket policy will allow any account in org to read
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Id: OrgAccessPolicy
        Statement:
        - Effect: Allow
          Principal:
            AWS: "*"
          Action: s3:GetObject
          Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3Bucket
              - /*
          Condition:
            StringEquals:
              aws:PrincipalOrgID: !Ref OrganizationId     
