# Sample buidspec for validation step
# This will install cloudformation linter, aws cli, and checkov
# The template will undergo multiple automated checks before being subjected to manual approval
# 1) cfn-lint check template integrity
# 2) aws cloudformation is used to validate the template (this step is here in case cfn-lint is out of date,
# but should really pick between step 1 and 2)
# 3) checkov performs cloudformation checks for security compliance, use --skip-check with a comma delimited list
# to skip any checks checkov requires, but you do not need. For more information on checkov CLI commands see (https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html)
version: 0.2
phases:

  install:
    commands:
      - pip install cfn-lint
      - pip install awscli
      - pip install checkov
  build:
    commands:
      - echo Build started on `date`
      - echo Starting CFN Linter Template Validation
      - cfn-lint --template "eq_s3_org_read_only.yml" --regions $AWS_REGION      
      - echo Starting CloudFormation Template Validation
      - aws cloudformation validate-template --template-body "file://$(pwd)/eq_s3_org_read_only.yml"     
      - echo Starting Checkov Security Compliance Check
      - checkov -d ./ --skip-check CKV_AWS_18,CKV_AWS_19
      
