name: Deploy CloudFormation Stack

# Only deploy if push occurs on main branch
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"

  workflow_dispatch:
    inputs:
      ManualTrigger:
        description: "Placeholder to manually trigger workflow"
        required: false
        default: "Yes" 
# Set Environment Variables
env:
  # ----------------------------------------
  # CloudFormation Stack Variables
  # ----------------------------------------
  # Name of AWS Stack to be created
  stackName: s3-bucket-github-stack

  # AWS Region where stack will be created 
  region: us-east-1

  # ----------------------------------------
  # CloudFormation Template Variables
  # (specific to template being deployed) 
  # ----------------------------------------
  # S3 Bucket Name
  S3BucketName: acme-devops-code-2
    
  # Organization Id limiting permissions to S3 bucket
  OrganizationId: o-j00zam5ytf
  
  # Approvers for manual approval
  Approvers: szamfir

# ----------------------------------------
# GitHub Job to be run
# 1) Checkout branch where this file resides
# 2) Configure AWS Credentials with repo secrets
# 3) Check template integrity
# 4) Deploy template to account/region 
# ----------------------------------------    
jobs:
  cfn-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}

      - name: Install CFN Linter
        run: pip install cfn-lint

      - name: Check Template Integrity
        run: cfn-lint --template "eq_s3_org_read_only.yml" --regions ${{ env.region }}

      - name: Manual Workflow Approval
        # You may pin to the exact commit or the version.
        # uses: trstringer/manual-approval@c4714a2254526b2f5d7edfe3e6477ee7a1e8e7b3
        uses: trstringer/manual-approval@v1.2.0
        with:
          approvers: ${{ env.Approvers }}
          secrets: ${{ secrets.APPROVAL_TOKEN }}

      - name: Deploy S3 Buckets CloudFormation Stacks
        id: s3-buckets
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name:  ${{ env.stackName }}
          template: eq_s3_org_read_only.yml
          parameter-overrides: "S3BucketName=${{ env.S3BucketName }}, OrganizationId=${{ env.OrganizationId }}"
