name: AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions
# You may pin to the exact commit or the version.
# uses: aws-actions/aws-cloudformation-github-deploy@dfbee8a4fec90af61b71bafda3890f8c4a2075ef
uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
with:
  # The name of the CloudFormation stack
  name: sgz-mycicd
  # The path or URL to the CloudFormation template
  template: eq_s3_org_read_only.yml
  # The comma-delimited list of stack template capabilities to acknowledge. Defaults to 'CAPABILITY_IAM'
  capabilities: 'CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND'
  # The parameters to override in the stack inputs. The list is comma-delimited, with each entry formatted as <ParameterName>=<ParameterValue>.
  parameter-overrides: 'pRepoName=acme-devops-code-2,OrganizationId=o-j00zam5ytf'
  # If the CloudFormation change set is empty, do not fail. Defaults to '0' (will fail on empty change set)
  #no-fail-on-empty-changeset: # optional, default is 0
  # Disable rollback of the stack if stack creation fails. Defaults to '0' (will rollback if stack creation fails). This input is only used for stack creation, not for stack update
  #disable-rollback: # optional, default is 0
  # The amount of time that can pass before the stack status becomes CREATE_FAILED. This input is only used for stack creation, not for stack update
  #timeout-in-minutes: # optional
  # The comma-delimited list of Amazon SNS topic ARNs to publish stack related events
  #notification-arns: # optional
  # The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that AWS CloudFormation assumes to create the stack. AWS CloudFormation uses the role's credentials to make calls on your behalf. AWS CloudFormation always uses this role for all future operations on the stack. As long as users have permission to operate on the stack, AWS CloudFormation uses this role even if the users don't have permission to pass it. Ensure that the role grants least privilege. If you don't specify a value, AWS CloudFormation uses the role that was previously associated with the stack
  #role-arn: # optional
  # Key-value pairs to associate with this stack. This input should be JSON-formatted, for example [ { "Key": "string", "Value": "string" } ]
  #tags: # optional
  # Whether to enable termination protection on the specified stack. Defaults to '0' (terminated protection will be disabled) This input is only used for stack creation, not for stack update
  #termination-protection: # optional, default is 0
