name: Deploy CloudFormation Stacks

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: true
        default: "us-east-1"
      bucketName:
        description: "S3 Bucket Name"
        required: true
        default: "acme-devops-code-2"
      organizationId:
        description: "Organization Id limiting permissions to S3 bucket"
        required: true
        default: "o-j00zam5ytf"

# You may pin to the exact commit or the version.
# uses: aws-actions/aws-cloudformation-github-deploy@dfbee8a4fec90af61b71bafda3890f8c4a2075ef
uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
with:
  role-to-assume: arn:aws:iam::077179288803:user/serban-github-prog-user
  aws-region: us-east-1
  jobs:
    cfndeployment:
      - name: Checkout
        uses: actions/checkout@v2

      name: Deploy to AWS Stack
      runs-on: ubuntu-latest
      # You may pin to the exact commit or the version.
      # uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
      steps:
        - name: Configure AWS Credentials
          id: creds
          uses: aws-actions/configure-aws-credentials@v1
          with:              
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ github.event.inputs.region }} 
        - name: Deploy S3 Buckets CloudFormation Stacks
          id: s3-buckets
          uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
          with:
            name:  s3-buckets
            template: eq_s3_org_read_only.yml
            parameter-overrides: >-
              BucketName=${{ github.event.inputs.bucketName }}
              OrganizationId= ${{ github.event.inputs.organizationId }}
